### ISSUE TITLE
Firebase permission denied

### ISSUE THREAD

**Issue by aliben** [Canner/apollo-link-firebase#7]
hello, i'am trying to use apollo link firebase  for a mutation query  but firebase seem to always give me permission denied while pushing data knowing that the firebase database rules are set to read and write by anyone.  what should i do. am i doing something wrong please help.

`@firebase/database: FIREBASE WARNING: set at /users/-LJ5L_J0V8OSC5KVbRJC failed: permission_denied` 

`service cloud.firestore {
  match /databases/{database}/documents {
    match /{document=**} {
      allow read, write: if true;
    }
  }
}`

here is the mutation query
`
 mutation PostMutation($description: String!, $url: String!) {
    post(input: {description :"hello" ,url: "hey"}) @rtdbPush(ref: "/users") {
      id @Key
      createdAt
      url
      description
    }
  }
`

`

**Comment by wwwy3y3** [comment]
@aliben You should set the security rules of realtime database not firestore.

Currently, apollo-link-firebase only supports realtime database.
