### ISSUE TITLE
Question: do you plan to further develop this?

### ISSUE THREAD

**Issue by shafqatevo** [Canner/apollo-link-firebase#8]
Hi, this is an excellent project with great utility. Seems work on this was stopped or did it move elsewhere? Is there any plan to continue working on this?

**Comment by wwwy3y3** [comment]
Hi @shafqatevo 

currently, the features supported already achieve what I need in my projects.

If you have any idea that could make this project better, we're open to discussion!

**Comment by shafqatevo** [comment]
Thanks @wwwy3y3!

We are very interested to port it to Dart to be used with graphql-flutter package and for the new Firestore database besides or instead of RTDB. graphql-flutter project has Link support in their latest codebase - https://github.com/zino-app/graphql-flutter/pull/76/commits/2205b940d8d7279e0a7d3e55d35e7d83b0f6c05a)

This is the missing piece now to use client-side-only GraphQL in Flutter or AngularDart with Firebase in a proper way. We'll basically wrap the Firebase Dart package with this Link, which is in turn a wrapper around Firebase JS SDK:

https://github.com/FirebaseExtended/firebase-dart

I am naively assuming this won't be much effort since you have a good structure already. One of our team members will work on this and we surely need some guidance from you and if you're also on Dart/Flutter-Firebase, we could work together.

**Comment by wwwy3y3** [comment]
@shafqatevo Firestore support sounds nice!

I did think about firestore before, but the API of firestore is more complicated than real-time database, and I didn't have time to think through the directives design of firestore.

We should have sth like this
```js
const query = gql`
  query getUsers {
    users @firestore(collection: "users", where: [{name: "country", operator: "==", value: "US"}]) {
      id
      name
    }
  }
`;
```

Maybe we can open another issue talking about firestore support, and I'd love to give you guys guidance and some technical support to support firestore in this module.

**Comment by shafqatevo** [comment]
Thanks @wwwy3y3 ! I will open another issue for this.
